/* 
 * Copyright (c) 2011, Hans-Kristian Arntzen <maister@archlinux.us>
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

enum sgl_key
{
   SGLK_UNKNOWN        = 0,
   SGLK_FIRST          = 0,
   SGLK_BACKSPACE      = 8,
   SGLK_TAB            = 9,
   SGLK_CLEAR          = 12,
   SGLK_RETURN         = 13,
   SGLK_PAUSE          = 19,
   SGLK_ESCAPE         = 27,
   SGLK_SPACE          = 32,
   SGLK_EXCLAIM        = 33,
   SGLK_QUOTEDBL       = 34,
   SGLK_HASH           = 35,
   SGLK_DOLLAR         = 36,
   SGLK_AMPERSAND      = 38,
   SGLK_QUOTE          = 39,
   SGLK_LEFTPAREN      = 40,
   SGLK_RIGHTPAREN     = 41,
   SGLK_ASTERISK       = 42,
   SGLK_PLUS           = 43,
   SGLK_COMMA          = 44,
   SGLK_MINUS          = 45,
   SGLK_PERIOD         = 46,
   SGLK_SLASH          = 47,
   SGLK_0              = 48,
   SGLK_1              = 49,
   SGLK_2              = 50,
   SGLK_3              = 51,
   SGLK_4              = 52,
   SGLK_5              = 53,
   SGLK_6              = 54,
   SGLK_7              = 55,
   SGLK_8              = 56,
   SGLK_9              = 57,
   SGLK_COLON          = 58,
   SGLK_SEMICOLON      = 59,
   SGLK_LESS           = 60,
   SGLK_EQUALS         = 61,
   SGLK_GREATER        = 62,
   SGLK_QUESTION       = 63,
   SGLK_AT             = 64,
   SGLK_LEFTBRACKET    = 91,
   SGLK_BACKSLASH      = 92,
   SGLK_RIGHTBRACKET   = 93,
   SGLK_CARET          = 94,
   SGLK_UNDERSCORE     = 95,
   SGLK_BACKQUOTE      = 96,
   SGLK_a              = 97,
   SGLK_b              = 98,
   SGLK_c              = 99,
   SGLK_d              = 100,
   SGLK_e              = 101,
   SGLK_f              = 102,
   SGLK_g              = 103,
   SGLK_h              = 104,
   SGLK_i              = 105,
   SGLK_j              = 106,
   SGLK_k              = 107,
   SGLK_l              = 108,
   SGLK_m              = 109,
   SGLK_n              = 110,
   SGLK_o              = 111,
   SGLK_p              = 112,
   SGLK_q              = 113,
   SGLK_r              = 114,
   SGLK_s              = 115,
   SGLK_t              = 116,
   SGLK_u              = 117,
   SGLK_v              = 118,
   SGLK_w              = 119,
   SGLK_x              = 120,
   SGLK_y              = 121,
   SGLK_z              = 122,
   SGLK_DELETE         = 127,

   SGLK_KP0            = 256,
   SGLK_KP1            = 257,
   SGLK_KP2            = 258,
   SGLK_KP3            = 259,
   SGLK_KP4            = 260,
   SGLK_KP5            = 261,
   SGLK_KP6            = 262,
   SGLK_KP7            = 263,
   SGLK_KP8            = 264,
   SGLK_KP9            = 265,
   SGLK_KP_PERIOD      = 266,
   SGLK_KP_DIVIDE      = 267,
   SGLK_KP_MULTIPLY    = 268,
   SGLK_KP_MINUS       = 269,
   SGLK_KP_PLUS        = 270,
   SGLK_KP_ENTER       = 271,
   SGLK_KP_EQUALS      = 272,

   SGLK_UP             = 273,
   SGLK_DOWN           = 274,
   SGLK_RIGHT          = 275,
   SGLK_LEFT           = 276,
   SGLK_INSERT         = 277,
   SGLK_HOME           = 278,
   SGLK_END            = 279,
   SGLK_PAGEUP         = 280,
   SGLK_PAGEDOWN       = 281,

   SGLK_F1             = 282,
   SGLK_F2             = 283,
   SGLK_F3             = 284,
   SGLK_F4             = 285,
   SGLK_F5             = 286,
   SGLK_F6             = 287,
   SGLK_F7             = 288,
   SGLK_F8             = 289,
   SGLK_F9             = 290,
   SGLK_F10            = 291,
   SGLK_F11            = 292,
   SGLK_F12            = 293,
   SGLK_F13            = 294,
   SGLK_F14            = 295,
   SGLK_F15            = 296,

   SGLK_NUMLOCK        = 300,
   SGLK_CAPSLOCK       = 301,
   SGLK_SCROLLOCK      = 302,
   SGLK_RSHIFT         = 303,
   SGLK_LSHIFT         = 304,
   SGLK_RCTRL          = 305,
   SGLK_LCTRL          = 306,
   SGLK_RALT           = 307,
   SGLK_LALT           = 308,
   SGLK_RMETA          = 309,
   SGLK_LMETA          = 310,
   SGLK_LSUPER         = 311,
   SGLK_RSUPER         = 312,
   SGLK_MODE           = 313,
   SGLK_COMPOSE        = 314,

   SGLK_HELP           = 315,
   SGLK_PRINT          = 316,
   SGLK_SYSREQ         = 317,
   SGLK_BREAK          = 318,
   SGLK_MENU           = 319,
   SGLK_POWER          = 320,
   SGLK_EURO           = 321,
   SGLK_UNDO           = 322,

   SGLK_LAST
};

